server:
  port: 8081

spring:
  application:
    name: my-first-service


# spring cloud gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka