
server:
  #port: 0 # use random port
  port: 8000

spring:
  application:
    name: user-service
  cloud:
    gateway:
      # GlobalFilter
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          # 이동 될 주소
          uri: http://localhost:8081/
          # 사용자가 입력한 조건값이 들어오면 앞에 주소로 이동
          predicates:
            - Path=/first-service/**
          # key, value
          filters:
#            - AddRequestHeader=first-request, first-request-header-2
#            - AddResponseHeader=first-response, first-response-header-2
            - CustomFilter # CustomFilter (java code)
            #- GlobalFilter # GlobalFilter (java code)

        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second-request, second-request-header-2
#            - AddResponseHeader=second-response, second-response-header-2
            - name : CustomFilter
            - name : LoggingFilter
              args:
                baseMessage: Hi, there
                preLogger: true
                postLogger: true
# spring cloud gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka


#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}  #?????? ?? ???? , ????? ???? ??, ?????
#  client:
#    register-with-eureka: true
#    fetch-registry:  true
#    server-url:
#      defaultZone: http://127.0.0.1:8761/eureka


